<?php $escape = $this->plugin('escapeHtml'); ?>
<?php $this->htmlElement('body')->appendAttribute('class', 'folksonomy tags browse'); ?>
<?php echo $this->pageTitle($this->translate('Folksonomy'), 2); ?>
<?php if (empty($tags)): ?>
<div class="no-resources">
    <p><?php echo $this->translate('There are no tags.'); ?></p>
</div>
<?php else: ?>
<?php $this->trigger('view.browse.before'); ?>
<?php echo $this->partial('folksonomy/common/tag-cloud', [
    'tags' => $tags,
    'resourceName' => '',
    'statuses' => ['allowed', 'approved'],
    'orderBy' => 'tag.name',
    'link' => true,
    'maxClasses' => 9,
    'tagNumbers' => 'after',
]); ?>
<?php $this->trigger('view.browse.after'); ?>
<?php endif; ?>
