<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

// Tags are already sorted.
$tagsByInitial = [];
if (extension_loaded('mbstring')) {
    foreach ($tags as $tag) {
        $initial = mb_substr($tag->name(), 0, 1);
        $tagsByInitial[mb_strtolower($initial)][] = $tag;
    }
} else {
    foreach ($tags as $tag) {
        $initial = substr($tag->name(), 0, 1);
        $tagsByInitial[strtolower($initial)][] = $tag;
    }
}
?>
<div id="tag-selector" class='selector sidebar active'>
    <a href="#" class="mobile-only sidebar-close o-icon-close"><span class="screen-reader-text"><?= $translate('Close Me') ?></span></a>
    <h3><?= $translate('Click on a tag to add it to the edit panel.') ?></h3>
    <input type="text" class="selector-filter" placeholder="<?= $escape($translate('Filter tags')) ?>">
    <ul>
        <li class="total-count-heading"><?= $translate('All tags') ?> (<span class="selector-total-count"><?= count($tags) ?></span>)
            <ul class="selectable-list">
                <?php foreach ($tagsByInitial as $initial => $tags): ?>
                    <li class="selector-parent">
                        <span><?= $initial ?></span>
                        (<span class="selector-child-count"><?= count($tagsByInitial[$initial]) ?></span>)
                        <ul>
                        <?php foreach ($tags as $tag): ?>
                            <li class="selector-child" data-child-search="<?= $escape($tag->name()) ?>" data-tag-internal-id="<?= $escape($tag->internalId()) ?>">
                                <span><?= $escape($tag->name()) ?></span>
                            </li>
                        <?php endforeach; ?>
                        </ul>
                <?php endforeach; ?>
            </ul>
        </li>
    </ul>
</div>
