<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var \Folksonomy\Form\TaggingForm $taggingForm
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$formElement = $plugins->get('formElement');
$assetUrl = $plugins->get('assetUrl');

$this->headLink()->appendStylesheet($assetUrl('css/folksonomy.css', 'Folksonomy'));
$this->headScript()->appendFile($assetUrl('js/folksonomy.js', 'Folksonomy'));
$taggingForm->prepare();
?>

<div class="property">
    <h4><?= $translate('New Tags') ?></h4>
    <?php // echo $this->form($taggingForm); ?>
    <?= $this->form()->openTag($taggingForm) ?>
    <?php $element = $taggingForm->get('o-module-folksonomy:tag-new'); ?>
    <div class="field">
        <div class="inputs">
            <?= $this->formText($element) ?>
        </div>
    </div>
    <?php if ($taggingForm->has('recaptcha')): ?>
    <?php $element = $taggingForm->get('recaptcha'); ?>
    <div class="field">
        <div class="inputs required">
            <?= $formElement($element) ?>
        </div>
    </div>
    <?php endif; ?>
    <?php if ($taggingForm->has('o-module-folksonomy:check')): /* honeyspot */ ?>
    <?php $element = $taggingForm->get('o-module-folksonomy:check'); ?>
    <div class="field">
        <div class="inputs required">
            <?= $formElement($element) ?>
        </div>
    </div>
    <?php endif; ?>
    <?php if ($taggingForm->has('legal_agreement')): ?>
    <?php $element = $taggingForm->get('legal_agreement'); ?>
    <div class="field">
        <div class="inputs required">
            <?= $this->setting('folksonomy_legal_text') ?>
            <?= $this->formCheckbox($element) ?>
        </div>
    </div>
    <?php endif; ?>
    <?= $formElement($taggingForm->get('resource_id')) ?>
    <?= $formElement($taggingForm->get('csrf_' . $resource->id())) ?>
    <?php $element = $taggingForm->get('submit'); ?>
    <?= $this->formButton()->openTag($element) ?>
    <?= $this->formLabel($element) ?>
    <?= $this->formButton()->closeTag() ?>
    <?= $this->form()->closeTag() ?>
</div>
