<?php
$translate = $this->plugin('translate');
$this->headLink()->appendStylesheet($this->assetUrl('css/folksonomy-admin.css', 'Folksonomy'));
$this->headScript()->appendFile($this->assetUrl('js/folksonomy-admin.js', 'Folksonomy'), 'text/javascript', ['defer' => 'defer']);
?>
<div class="folksonomy">
<?php if (empty($tags)): ?>
    <div class="no-resources">
        <p><?php echo $translate('There are no tags for this resource.'); ?></p>
    </div>
<?php else: ?>
    <?php
    $escape = $this->plugin('escapeHtml');
    $resourceName = $resource->getControllerName();
    $updateRight = $this->userIsAllowed(\Folksonomy\Entity\Tagging::class, 'update');
    ?>
    <ul>
    <?php foreach ($tags as $tag): ?>
        <?php $tagging = $taggings[$tag->name()]; ?>
        <li class="value tag"><?php echo $this->hyperlink($tag->name(), $tag->urlResources($resourceName)); ?>
            <?php if ($updateRight): ?>
            <span class="single actions"><a href="#"
                class="status-toggle o-icon-<?php echo $tagging->status() ?: 'undefined'; ?>"
                data-status-toggle-url="<?php echo $escape($tagging->url('toggle-status')); ?>"
                data-status="<?php echo $tagging->status(); ?>"
                aria-label="<?php echo $escape($translate('Toggle status')); ?>"
                title="<?php echo $escape($translate('Toggle status')); ?>"></a></span>
            <?php else: ?>
            <span class="no-action o-icon-<?php echo $tagging->status() ?: 'undefined'; ?>"></span>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
    </ul>
<?php endif; ?>
</div>
