<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/folksonomy-admin.css', 'Folksonomy'));
$this->headScript()->appendFile($this->assetUrl('js/folksonomy-admin.js', 'Folksonomy'));
$escape = $this->plugin('escapeHtml');
$removeStr = $escape($this->translate('Remove tag'));
$tagTemplate = '
<tr>
    <td class="tag-name"></td>
    <td>
        <ul class="actions">
            <li>
                <a href="#" class="o-icon-delete" title="' . $removeStr . '" aria-label="' . $removeStr . '"></a>
            </li>
        </ul>
        <input type="hidden" name="o-module-folksonomy:tag[]">
    </td>
</tr>';
?>
<fieldset id="tags" class="section" aria-labelledby="tags-label">
    <legend id="tags-legend"><?php echo $this->translate('Tags'); ?></legend>
    <table id="resource-tags" data-tablesaw-mode="stack" class="tablesaw tablesaw-stack <?php echo ($resource && $tags) ? '' : 'empty'; ?>">
        <thead>
        <tr>
            <th><?php echo $this->translate('Tag'); ?></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php
        if ($resource && $tags):
            $resourceName = $resource->getControllerName();
            $resourceName = in_array($resourceName, ['item-set', 'item', 'media']) ? $resourceName : null;
        ?>
        <?php foreach ($tags as $tag): ?>
        <tr>
            <td><?php echo $this->hyperlink($tag->name(), $tag->urlResources($resourceName)); ?></td>
            <td>
                <ul class="actions">
                    <li>
                        <a href="#" class="o-icon-delete" title=" <?php echo $removeStr; ?>" aria-label=" <?php echo $removeStr; ?>"></a>
                    </li>
                </ul>
                <input type="hidden" name="o-module-folksonomy:tag[]" value="<?php echo $escape($tag->name()) ?>">
            </td>
        </tr>
        <?php endforeach; ?>
        <?php endif; ?>
        </tbody>
    </table>
    <div class="no-resources">
        <p>
            <?php echo $this->translate('There are no tags for this resource.'); ?>
            <br />
            <?php echo $this->translate('Add existing ones using the interface to the right or add new ones in the field below.'); ?>
        </p>
    </div>
    <div class="field">
        <div class="inputs">
            <input name="o-module-folksonomy:tag-new" value="" placeholder="<?php echo $this->translate('Add one or multiple comma-separated new tags'); ?>" class="touched" type="text">
        </div>
    </div>
    <button id="tag-selector-button" class="mobile-only"><?php echo $this->translate('Add a tag'); ?></button>
    <span id="tag-template" data-template="<?php echo $escape($tagTemplate); ?>"></span>
    <?php echo $this->tagSelector(); ?>
</fieldset>
