<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/folksonomy-admin.css', 'Folksonomy'));
?>
<div id="tags" class="section">
<?php if (empty($tags)): ?>
    <div class="no-resources">
        <p><?php echo $this->translate('There are no tags for this resource.'); ?></p>
    </div>
<?php else: ?>
    <?php $resourceName = $resource->getControllerName();
    $resourceName = in_array($resourceName, ['item-set', 'item', 'media']) ? $resourceName : null; ?>
    <ul class="tags">
        <?php foreach ($tags as $tag): ?>
        <li><?php echo $this->hyperlink($tag->name(), $tag->urlResources($resourceName)); ?></li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
</div>
