<?php
if ($tags):
    $resourceName = $resource->getControllerName();
    $resourceName = in_array($resourceName, ['item-set', 'item', 'media']) ? $resourceName : null;
?>
<div class="meta-group">
    <h4><?php echo $this->translate('Tags'); ?></h4>
    <?php foreach ($tags as $tag): ?>
    <div class="value tag"><?php echo $this->hyperlink($tag->name(), $tag->urlResources($resourceName)); ?></div>
    <?php endforeach; ?>
</div>
<?php endif; ?>
