<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var string $heading
 */
?>

<?php if ($heading = $block->dataValue('heading')): ?>
<h2><?= $this->escapeHtml($heading) ?></h2>
<?php endif; ?>

<?= $this->partial('common/tag-cloud', [
    'tags' => null,
    'resourceName' => $block->dataValue('resource_name', ''),
    // Never display "rejected" tags, in all cases.
    // The "proposed" status may be filtered via the visibility filter.
    'statuses' => ['allowed', 'approved', 'proposed'],
    'orderBy' => 'tag.name',
    'link' => true,
    'maxClasses' => $block->dataValue('max_classes', 9),
    'tagNumbers' => $block->dataValue('tag_numbers', false),
]) ?>
