<?php
use Folksonomy\Api\Adapter\TagAdapter;

$escape = $this->plugin('escapeHtml');
$this->headLink()->appendStylesheet($this->assetUrl('css/folksonomy-admin.css', 'Folksonomy'));
$this->headScript()->appendFile($this->assetUrl('js/folksonomy-admin.js', 'Folksonomy'));
$this->htmlElement('body')->appendAttribute('class', 'folksonomy tags browse');
$sortHeadings = [
    [
        'label' => $this->translate('Tag'),
        'value' => 'name'
    ],
    [
        'label' => $this->translate('Total count'),
        'value' => 'count'
    ],
    [
        'label' => $this->translate('Total item sets'),
        'value' => 'item_sets'
    ],
    [
        'label' => $this->translate('Total items'),
        'value' => 'items'
    ],
    [
        'label' => $this->translate('Total media'),
        'value' => 'media'
    ],
    [
        'label' => $this->translate('Recent'),
        'value' => 'recent'
    ],
];
$updateRight = $this->userIsAllowed(TagAdapter::class, 'update');
$deleteRight = $this->userIsAllowed(TagAdapter::class, 'delete');
?>

<?php echo $this->pageTitle($this->translate('Tags')); ?>

<?php echo $this->searchFilters(); ?>

 <div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php // echo $this->hyperlink($this->translate('Advanced search'), $this->url(null, ['action' => 'search'], ['query' => $this->params()->fromQuery()], true), ['class' => 'advanced-search']); ?>
    <?php echo $this->sortSelector($sortHeadings); ?>
</div>

<form method="post" id="batch-form" class="disable-unsaved-warning">

<?php if ($tags): ?>
<div id="page-actions">
    <?php if ($this->userIsAllowed(TagAdapter::class, 'delete')): ?>
    <a href="#"
        class="button delete batch-actions sidebar-content"
        data-sidebar-content-url="<?php echo $escape($this->url(null, ['action' => 'batch-delete-confirm'], true)); ?>"
        aria-label="<?php echo $escape($this->translate('Delete')); ?>"
        title="<?php echo $escape($this->translate('Delete')); ?>"><?php echo $escape($this->translate('Delete')); ?></a>
    <?php endif; ?>
</div>
<?php endif; ?>

<?php $this->trigger('view.browse.before'); ?>
<?php if (empty($tags)): ?>
<div class="no-resources">
    <p><?php echo $this->translate('There are no tags.'); ?></p>
</div>
<?php $this->trigger('view.browse.after'); ?>
<?php else: ?>
<table class="tablesaw <?php if ($deleteRight) echo 'batch-edit'; ?>" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th class="column-tag">
                <?php if ($deleteRight): ?>
                <input type="checkbox" class="select-all">
                <?php endif; ?>
                <?php echo $this->translate('Tag'); ?>
            </th>
            <th><?php echo $this->translate('Total count'); ?></th>
            <th><?php echo $this->translate('Item sets'); ?></th>
            <th><?php echo $this->translate('Items'); ?></th>
            <th><?php echo $this->translate('Media'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($tags as $tag):
            $name = $tag->name();
        ?>
        <tr>
            <td>
                <?php if ($deleteRight): ?>
                    <input type="checkbox" name="resource_ids[]" value="<?php echo $tag->id(); ?>">
                <?php endif; ?>
                <span class="tag-name"<?php
                    if ($updateRight) echo ' contenteditable="true" data-update-url="' . $tag->url('update') . '"';
                ?>><?php
                    echo $name;
                ?></span>
                <ul class="actions">
                    <?php if ($updateRight): ?>
                    <li><a href="#"
                        class="o-icon-edit contenteditable"
                        aria-label="<?php echo $escape($this->translate('Edit name')); ?>"
                        title="<?php echo $escape($this->translate('Edit name')); ?>"></a></li>
                    <?php endif; ?>
                    <?php if ($deleteRight): ?>
                    <li><a href="#"
                        class="o-icon-delete sidebar-content"
                        data-sidebar-content-url="<?php echo $escape($tag->url('delete-confirm')); ?>"
                        aria-label="<?php echo $escape($this->translate('Delete')); ?>"
                        title="<?php echo $escape($this->translate('Delete')); ?>"></a></li>
                    <?php endif; ?>
                </ul>
            </td>
            <td><?php if ($tagCount[$name]['count']) echo $tagCount[$name]['count']; ?></td>
            <td><?php if ($tagCount[$name]['item_sets']) echo $this->hyperlink(
                $tagCount[$name]['item_sets'], $tag->urlResources('item-set'), ['class' => 'tag-browse-item-sets']
            ); ?></td>
            <td><?php if ($tagCount[$name]['items']) echo $this->hyperlink(
                $tagCount[$name]['items'], $tag->urlResources('item'), ['class' => 'tag-browse-items']
            ); ?></td>
            <td><?php if ($tagCount[$name]['media']) echo $this->hyperlink(
                $tagCount[$name]['media'], $tag->urlResources('media'), ['class' => 'tag-browse-media']
            ); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

</form>

<?php $this->trigger('view.browse.after'); ?>
<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?php echo $escape($this->translate('Close')); ?>"
        title="<?php echo $escape($this->translate('Close')); ?>"></a>
    <div class="sidebar-content"></div>
</div>

<script>
// Complete the batch delete form after confirmation.
$('.sidebar').on('submit', '#batch-delete-confirm', function(e) {
    var confirmForm = $(this);
    if (confirmForm.hasClass('batch-delete-all')) {
        confirmForm.append($('.batch-query').clone());
    } else {
        $('#batch-form').find('input:checked').each(function() {
            confirmForm.append($(this).clone().attr('type', 'hidden'));
        });
    }
});
</script>
<?php endif; ?>
