<?php
use Folksonomy\Api\Adapter\TagAdapter;

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->headLink()->appendStylesheet($this->assetUrl('css/folksonomy-admin.css', 'Folksonomy'));
$this->headScript()->appendFile($this->assetUrl('js/folksonomy-admin.js', 'Folksonomy'), 'text/javascript', ['defer' => 'defer']);
$this->htmlElement('body')->appendAttribute('class', 'folksonomy tags browse');
$sortHeadings = [
    [
        'label' => $translate('Tag'),
        'value' => 'name',
    ],
    [
        'label' => $translate('Total count'),
        'value' => 'total',
    ],
    [
        'label' => $translate('Total item sets'),
        'value' => 'item_sets',
    ],
    [
        'label' => $translate('Total items'),
        'value' => 'items',
    ],
    [
        'label' => $translate('Total media'),
        'value' => 'media',
    ],
    [
        'label' => $translate('Recent'),
        'value' => 'recent',
    ],
];
$updateRight = $this->userIsAllowed(TagAdapter::class, 'update');
$deleteRight = $this->userIsAllowed(TagAdapter::class, 'delete');
?>

<?= $this->pageTitle($translate('Tags')) ?>

<?= $this->searchFilters() ?>

 <div class="browse-controls">
    <?= $this->pagination() ?>
    <?php // echo $this->hyperlink($translate('Advanced search'), $this->url(null, ['action' => 'search'], ['query' => $this->params()->fromQuery()], true), ['class' => 'advanced-search']); ?>
    <?= $this->sortSelector($sortHeadings) ?>
</div>

<form method="post" id="batch-form" class="disable-unsaved-warning">

<?php if ($tags): ?>
<div id="page-actions">
    <?php if ($this->userIsAllowed(TagAdapter::class, 'delete')): ?>
    <a href="#"
        class="button delete batch-actions sidebar-content"
        data-sidebar-content-url="<?= $escape($this->url(null, ['action' => 'batch-delete-confirm'], true)) ?>"
        aria-label="<?= $escape($translate('Delete')) ?>"
        title="<?= $escape($translate('Delete')) ?>"><?= $escape($translate('Delete')) ?></a>
    <?php endif; ?>
</div>
<?php endif; ?>

<?php $this->trigger('view.browse.before'); ?>
<?php if (empty($tags)): ?>
<div class="no-resources">
    <p><?= $translate('There are no tags.') ?></p>
</div>
<?php $this->trigger('view.browse.after'); ?>
<?php else: ?>
<table class="tablesaw <?php if ($deleteRight) echo 'batch-edit'; ?>" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th class="column-tag">
                <?php if ($deleteRight): ?>
                <input type="checkbox" class="select-all">
                <?php endif; ?>
                <?= $translate('Tag') ?>
            </th>
            <th><?= $translate('Total count') ?></th>
            <th><?= $translate('Item sets') ?></th>
            <th><?= $translate('Items') ?></th>
            <th><?= $translate('Media') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($tags as $tag):
            $name = $tag->name();
        ?>
        <tr>
            <td>
                <?php if ($deleteRight): ?>
                    <input type="checkbox" name="resource_ids[]" value="<?= $this->escapeHtml($tag->id()) ?>">
                <?php endif; ?>
                <span class="tag-name"<?php
                    if ($updateRight) echo ' contenteditable="true" data-update-url="' . $tag->url('update') . '"';
                ?>><?php
                    echo $name;
                ?></span>
                <ul class="actions">
                    <?php if ($updateRight): ?>
                    <li><a href="#"
                        class="o-icon-edit contenteditable"
                        aria-label="<?= $escape($translate('Edit name')) ?>"
                        title="<?= $escape($translate('Edit name')) ?>"></a></li>
                    <?php endif; ?>
                    <?php if ($deleteRight): ?>
                    <li><a href="#"
                        class="o-icon-delete sidebar-content"
                        data-sidebar-content-url="<?= $escape($tag->url('delete-confirm')) ?>"
                        aria-label="<?= $escape($translate('Delete')) ?>"
                        title="<?= $escape($translate('Delete')) ?>"></a></li>
                    <?php endif; ?>
                </ul>
            </td>
            <td><?php if ($tagCount[$name]['total']) echo $tagCount[$name]['total']; ?></td>
            <td><?php if ($tagCount[$name]['item_sets']) echo $this->hyperlink(
                $tagCount[$name]['item_sets'], $tag->urlResources('item-set'), ['class' => 'tag-browse-item-sets']
            ); ?></td>
            <td><?php if ($tagCount[$name]['items']) echo $this->hyperlink(
                $tagCount[$name]['items'], $tag->urlResources('item'), ['class' => 'tag-browse-items']
            ); ?></td>
            <td><?php if ($tagCount[$name]['media']) echo $this->hyperlink(
                $tagCount[$name]['media'], $tag->urlResources('media'), ['class' => 'tag-browse-media']
            ); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

</form>

<?php $this->trigger('view.browse.after'); ?>
<div class="browse-controls">
    <?= $this->pagination() ?>
</div>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?= $escape($translate('Close')) ?>"
        title="<?= $escape($translate('Close')) ?>"></a>
    <div class="sidebar-content"></div>
</div>

<script>
// Complete the batch delete form after confirmation.
$('.sidebar').on('submit', '#batch-delete-confirm', function(e) {
    var confirmForm = $(this);
    if (confirmForm.hasClass('batch-delete-all')) {
        confirmForm.append($('.batch-query').clone());
    } else {
        $('#batch-form').find('input:checked').each(function() {
            confirmForm.append($(this).clone().attr('type', 'hidden'));
        });
    }
});
</script>
<?php endif; ?>
