<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var \Folksonomy\Api\Representation\TagRepresentation[] $tags
 */

?>

<?php
if (count($tags)) {
    $escape = $this->plugin('escapeHtml');

    $tagStrings = [];
    if (isset($link) && $link === false) {
        foreach ($tags as $tag) {
            $tagStrings[] = $escape($tag->name());
        }
    } else {
        $hyperlink = $this->plugin('hyperlink');
        $resourceName = $resource->getControllerName();
        foreach ($tags as $tag) {
            $tagStrings[] = $hyperlink($tag->name(), $tag->urlResources($resourceName));
        }
    }

    if (!isset($delimiter)) {
        $delimiter = ', ';
    }
    echo join($escape($delimiter), $tagStrings);
}
