<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var \Folksonomy\Api\Representation\TagRepresentation[] $tags
 */

?>

<?php
if ($tags):
    $translate = $this->plugin('translate');
    $hyperlink = $this->plugin('hyperlink');

    // In public view, only items (default) and item sets are available.
    $resourceName = $resource->getControllerName() === 'item-set' ? 'item-set' : null;
?>
<div class="property tags">
    <h4><?= $translate('Tags') ?></h4>
    <?php foreach ($tags as $tag): ?>
    <div class="value tag"><?= $hyperlink($tag->name(), $tag->urlResources($resourceName)) ?></div>
    <?php endforeach; ?>
</div>
<?php endif; ?>
