<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Laminas\Form\Form $form
 */

$translate = $this->plugin('translate');
?>

<div id="sidebar-confirm">
    <h3><?= $translate('Delete taggings') ?></h3>
    <p><?= $translate('Are you sure you would like to delete the selected taggings?') ?></p>
    <p><?= sprintf($translate('Note: This won’t delete tags: check the %stags page%s to manage them.'),
        '<a href="' . $this->url('admin/tag') . '">', '</a>') ?></p>
    <?= $this->form($this->form) ?>
</div>
