<?php
use Folksonomy\Api\Adapter\TaggingAdapter;

$escape = $this->plugin('escapeHtml');
$this->headLink()->appendStylesheet($this->assetUrl('css/folksonomy-admin.css', 'Folksonomy'));
$this->headScript()->appendFile($this->assetUrl('js/folksonomy-admin.js', 'Folksonomy'));
$this->htmlElement('body')->appendAttribute('class', 'folksonomy taggings browse');
$sortHeadings = [
    // [
    //     'label' => $this->translate('Resource'),
    //     'value' => 'resource_title'
    // ],
    [
        'label' => $this->translate('Tag'),
        'value' => 'tag_name'
    ],
    [
        'label' => $this->translate('Status'),
        'value' => 'status'
    ],
    [
        'label' => $this->translate('Tagger'),
        'value' => 'owner_name'
    ],
    [
        'label' => $this->translate('Date tagged'),
        'value' => 'created'
    ],
];
$batchEditRight = $this->userIsAllowed(TaggingAdapter::class, 'batch-update')
    || $this->userIsAllowed(TaggingAdapter::class, 'batch-delete');
$editRight = $this->userIsAllowed(TaggingAdapter::class, 'update')
    || $this->userIsAllowed(TaggingAdapter::class, 'delete');
?>

<?php echo $this->pageTitle($this->translate('Taggings')); ?>

<?php echo $this->searchFilters(); ?>

 <div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php // echo $this->hyperlink($this->translate('Advanced search'), $this->url(null, ['action' => 'search'], ['query' => $this->params()->fromQuery()], true), ['class' => 'advanced-search']); ?>
    <?php echo $this->sortSelector($sortHeadings); ?>
</div>

<form method="post" id="batch-form" class="disable-unsaved-warning">

<?php if ($taggings): ?>
<div id="page-actions">
    <?php if ($this->userIsAllowed(TaggingAdapter::class, 'batch-update')): ?>
    <a href="#"
        class="button batch-actions status-batch"
        data-status-batch-url="<?php echo $escape($this->url(null, ['action' => 'batch-approve'], true)); ?>"
        data-status="approve"
        aria-label="<?php echo $escape($this->translate('Approve')); ?>"
        title="<?php echo $escape($this->translate('Approve')); ?>"><?php echo $escape($this->translate('Approve')); ?></a>
    <a href="#"
        class="button batch-actions status-batch"
        data-status-batch-url="<?php echo $escape($this->url(null, ['action' => 'batch-reject'], true)); ?>"
        data-status="reject"
        aria-label="<?php echo $escape($this->translate('Reject')); ?>"
        title="<?php echo $escape($this->translate('Reject')); ?>"><?php echo $escape($this->translate('Reject')); ?></a>
    <?php endif; ?>
    <?php if ($this->userIsAllowed(TaggingAdapter::class, 'batch-delete')): ?>
    <a href="#"
        class="button delete batch-actions sidebar-content"
        data-sidebar-content-url="<?php echo $escape($this->url(null, ['action' => 'batch-delete-confirm'], true)); ?>"
        aria-label="<?php echo $escape($this->translate('Delete')); ?>"
        title="<?php echo $escape($this->translate('Delete')); ?>"><?php echo $escape($this->translate('Delete')); ?></a>
    <?php endif; ?>
</div>
<?php endif; ?>

<?php $this->trigger('view.browse.before'); ?>
<?php if (empty($taggings)): ?>
<div class="no-resources">
    <p><?php echo $this->translate('There are no taggings.'); ?></p>
</div>
<?php $this->trigger('view.browse.after'); ?>

<?php else: ?>
<table class="tablesaw <?php if ($batchEditRight) echo 'batch-edit'; ?>" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th class="column-tag">
                <?php if ($batchEditRight): ?>
                <input type="checkbox" class="select-all">
                <?php endif; ?>
                <?php echo $this->translate('Tag'); ?>
            </th>
            <th><?php echo $this->translate('Status'); ?></th>
            <th><?php echo $this->translate('Resource'); ?></th>
            <th><?php echo $this->translate('Tagger'); ?></th>
            <th><?php echo $this->translate('Date tagged'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($taggings as $tagging): ?>
        <?php
        $status = $tagging->status() ?: 'undefined';
        $tag = $tagging->tag();
        $resource = $tagging->resource();
        if ($owner = $tagging->owner()) {
            $ownerText = $this->hyperlink(
                $owner->name(),
                $this->url('admin/id', ['controller' => 'user', 'action' => 'show', 'id' => $owner->id()])
            );
        } else {
            $ownerText = $this->translate('[no owner]');
        }
        ?>
        <tr>
            <td>
                <?php if ($batchEditRight): ?>
                    <input type="checkbox" name="resource_ids[]" value="<?php echo $tagging->id(); ?>">
                <?php endif; ?>
                <?php if ($tag): ?>
                <span class="tag-name"><?php echo $this->hyperlink($tag->name(), $tag->urlResources()); ?></span>
                <span class="is-public-or-not<?php if (!$tagging->isPublic()) echo ' o-icon-private'; ?>" aria-label="<?php echo $this->translate('Private'); ?>"></span>
                <?php else: ?>
                <span class="tag-name no-tag">[<?php echo $this->translate('Removed'); ?>]</span>
                <span class="is-public-or-not o-icon-private" aria-label="<?php echo $this->translate('Private'); ?>"></span>
                <?php endif;?>
                <ul class="actions">
                <?php $editRightTagging = $tagging->userIsAllowed('update'); ?>
                    <?php if ($editRightTagging): ?>
                        <?php if ($tag): ?>
                    <li><a href="#"
                        class="status-toggle o-icon-<?php echo $status; ?>"
                        data-status-toggle-url="<?php echo $escape($tagging->url('toggle-status')); ?>"
                        data-status="<?php echo $status; ?>"
                        aria-label="<?php echo $escape($this->translate('Toggle status')); ?>"
                        title="<?php echo $escape($this->translate('Toggle status')); ?>"></a></li>
                        <?php else: ?>
                    <li><span class="status-toggle o-icon-none"></span></li>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($tagging->userIsAllowed('delete')): ?>
                    <li><a href="#"
                        class="o-icon-delete sidebar-content"
                        data-sidebar-content-url="<?php echo $escape($tagging->url('delete-confirm')); ?>"
                        aria-label="<?php echo $escape($this->translate('Delete')); ?>"
                        title="<?php echo $escape($this->translate('Delete')); ?>"></a></li>
                    <?php endif; ?>
                </ul>
            </td>
            <td class="status-label"><?php
            if (!$editRightTagging):
            ?><span class="no-action o-icon-<?php echo $tagging->status() ?: 'undefined'; ?>"></span><?php
            endif;
            echo $escape($tagging->statusLabel());
            ?></td>
            <td>
                <?php if ($resource): ?>
                    <?php echo $resource->link($resource->displayTitle()); ?>
                <span class="resource-name <?php echo $resource->getControllerName(); ?>" aria-label="<?php echo $this->translate($resource->getControllerName()); ?>"></span>
                <?php else: ?>
                    [<?php echo $this->translate('Removed'); ?>]
                <span class="resource-name no-resource"></span>
                <?php endif; ?>
            </td>
            <td><?php echo $ownerText; ?></td>
            <td><?php echo $escape($this->i18n()->dateFormat($tagging->created())); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

</form>

<?php $this->trigger('view.browse.after'); ?>
<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?php echo $escape($this->translate('Close')); ?>"
        title="<?php echo $escape($this->translate('Close')); ?>"></a>
    <div class="sidebar-content"></div>
</div>

<script>
// Complete the batch delete form after confirmation.
$('.sidebar').on('submit', '#batch-delete-confirm', function(e) {
    var confirmForm = $(this);
    if (confirmForm.hasClass('batch-delete-all')) {
        confirmForm.append($('.batch-query').clone());
    } else {
        $('#batch-form').find('input:checked').each(function() {
            confirmForm.append($(this).clone().attr('type', 'hidden'));
        });
    }
});
</script>
<?php endif; ?>
