<?php $escape = $this->plugin('escapeHtml'); ?>
<?php $tagging = $resource; ?>
<div class="resource-details" data-resource-values="<?php //echo $escape($values); ?>">
    <h3 class="o-module-folksonomy-tagging"><?php echo $tagging->link(sprintf($this->translate('Tagging #%d'), $tagging->id())); ?></h3>
    <div class="meta-group">
        <h4><?php echo $escape($this->translate('Tag')); ?></h4>
        <div class="value">
        <?php if ($tag = $tagging->tag()): ?>
            <span class="tag-name"><?php echo $this->hyperlink($tag->name(), $tag->urlResources()); ?></span>
            <span class="tag-internal-id">(#<?php echo $tag->internalId(); ?>)</span>
        <?php else: ?>
            <span class="tag-name no-tag"><?php echo $this->translate('[Removed]'); ?></span>
        <?php endif;?>
        </div>
    </div>
    <div class="meta-group">
        <?php $resource = $tagging->resource(); ?>
        <h4><?php echo $escape($this->translate('Resource')); ?> <span class="fa resource-name <?php echo $resource ? $resource->getControllerName() : 'no-resource'; ?>"></span></h4>
        <div class="value">
        <?php if ($resource): ?>
        <span class="resource-name">
            <?php echo $resource->link($resource->displayTitle()); ?>
        </span>
            <?php if (!$resource->isPublic()): ?>
        <span class="o-icon-private"></span>
            <?php endif; ?>
        <?php else: ?>
        <span class="resource-name no-resource">
            [<?php echo $this->translate('Removed'); ?>]
        </span>
        <?php endif; ?>
        </div>
    </div>
    <div class="meta-group">
        <h4><?php echo $escape($this->translate('Tagger')); ?></h4>
        <div class="value"><?php
        if ($owner = $tagging->owner()) {
            echo $this->hyperlink(
                $owner->name(),
                $this->url('admin/id', ['controller' => 'user', 'action' => 'show', 'id' => $owner->id()])
            );
        } else {
            echo $this->translate('[no owner]');
        }
        ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $escape($this->translate('Status')); ?></h4>
        <div class="value"><?php echo $tagging->statusLabel() . ' (' . ($tagging->isPublic() ? $this->translate('Public') : $this->translate('Private')) . ')'; ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Date Created'); ?></h4>
        <div class="value"><?php echo $escape($this->i18n()->dateFormat($tagging->created())); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $this->translate('Date Modified'); ?></h4>
        <div class="value"><?php echo $escape($this->i18n()->dateFormat($tagging->modified())); ?></div>
    </div>
</div>
